trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*

extends:
  template: /eng/pipelines/templates/common.yml
  parameters:
    IncludeRelease: ${{ or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'IndividualCI')) }}
