trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*

extends:
  template: /eng/pipelines/templates/common.yml
  parameters:
    # We release signed, manual runs from main and hotfix branches
    # All other runs get -alpha prerelease labels
    PublishPackages: ${{ ne(variables['Build.Reason'], 'PullRequest') }}
    RunLiveTests: true
    #TODO: commented out for testing add back before merging
    #ReleaseRun: ${{ and(eq(variables['Build.Reason'], 'Manual'), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startswith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))) }}
    ReleaseRun: true
