parameters:
- name: QuickBuild
  displayName: Quick Build (Skip signing and slow arguments)
  type: boolean
  default: false
  
trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*

extends:
  template: /eng/pipelines/templates/common.yml
  parameters:
    QuickBuild: ${{ parameters.QuickBuild }}
    # We release manual runs, but not from PR refs
    ReleaseRun: ${{ and(eq(variables['Build.Reason'], 'Manual'), not(startswith(variables['Build.SourceBranch'], 'refs/pull/'))) }}
