parameters:
- name: TimeoutInMinutes
  type: number
  default: 120

jobs:
- job: Analyze
  condition: and(succeededOrFailed(), ne(variables['Skip.Analyze'], 'true'))
  timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
  dependsOn: []
  steps:
  - checkout: self
  
  - task: UseDotNet@2
    displayName: "Use .NET SDK from global.json"
    retryCountOnTaskFailure: 3
    inputs:
      useGlobalJson: true

  - task: Powershell@2
    displayName: "Run source analysis"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Analyze-Code.ps1

  - template: /eng/common/pipelines/templates/steps/check-spelling.yml
    parameters:
      ContinueOnError: false

  # Link detection into private repos is not supported.
  # TODO: Uncomment when the repo is public
  # - template: /eng/common/pipelines/templates/steps/verify-links.yml
  #   parameters:
  #     Condition: succeededOrFailed()
  #     Directory: ""
  #     CheckLinkGuidance: $true
  #     ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  #       Urls: (eng/common/scripts/get-markdown-files-from-changed-files.ps1)
