jobs:
- job: AOTCompatibilityAnalysis
  displayName: "AOT Compatibility Analysis"
  pool:
    name: $(LINUXPOOL)
    image: $(LINUXVMIMAGE)
    os: linux
  steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: "Use .NET SDK from global.json"
    retryCountOnTaskFailure: 3
    inputs:
      useGlobalJson: true

  - task: PowerShell@2
    displayName: "Generate AOT Compatibility Report"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Generate-AOTCompactReport.ps1
      arguments: >
        -Runtime 'linux-x64'
        -GenerateHtml:$false
      workingDirectory: $(Build.SourcesDirectory)
    continueOnError: true

  - task: PowerShell@2
    displayName: "Display AOT Analysis Report"
    condition: always()
    inputs:
      pwsh: true
      targetType: 'inline'
      script: |
        $jsonPath = "$(Build.SourcesDirectory)/.work/aotCompactReport/aot-compact-report.json"
        
        if (Test-Path $jsonPath) {
          $jsonContent = Get-Content $jsonPath -Raw
          $jsonObject = $jsonContent | ConvertFrom-Json
          $totalWarnings = 0
          $dllCount = 0
          
          if ($jsonObject -is [PSCustomObject]) {
            foreach ($property in $jsonObject.PSObject.Properties) {
              $dllCount++
              $totalWarnings += $property.Value.Count
            }
          }
          
          Write-Host "##[section]AOT Compatibility Analysis Results"
          Write-Host "Total AOT/Trimming Warnings: $totalWarnings"
          Write-Host "Affected DLLs: $dllCount"
          Write-Host ""
          Write-Host "##[section]Full AOT Analysis Report (JSON):"
          Write-Host $jsonContent
          
          if ($totalWarnings -gt 0) {
            Write-Host ""
            Write-Host "##[warning]AOT compatibility issues found. See artifacts for details."
            Write-Host "##vso[task.logissue type=warning]$totalWarnings AOT/trimming warnings found across $dllCount DLLs"
          } else {
            Write-Host "##[section]✅ No AOT compatibility issues found!"
          }
        } else {
          Write-Host "##[error]AOT analysis report not found"
        }

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.SourcesDirectory)/.work/aotCompactReport
      ArtifactName: AOTCompatibilityReport
      CustomCondition: always()
