parameters:
# required matrix parameters
- name: UsePlatformContainer
  type: boolean
- name: OSName
  type: string
- name: Matrix
  type: object
- name: DependsOn
  type: string
- name: CloudConfig
  type: object

jobs:
- job: Build_${{ parameters.OSName }}
  displayName: "Build"
  dependsOn:
  - Initialize
  - ${{ parameters.DependsOn }}
  strategy:
    matrix: $[ ${{ parameters.Matrix }} ]
  pool:
    name: $(Pool)
    ${{ if eq(parameters.OSName, 'macOS') }}:
      vmImage: $(OSVmImage)
    ${{ else }}:
      image: $(OSVmImage)
    os: ${{ parameters.OSName }}
  variables:
    Version: $[ dependencies.Initialize.outputs['Version.Version'] ]
  steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: "Use .NET SDK from global.json"
    retryCountOnTaskFailure: 3
    inputs:
      useGlobalJson: true

  - task: Powershell@2
    displayName: "Build module"
    condition: and(succeeded(), ne(variables['NoPackagesChanged'],'true'))
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Build-Module.ps1
      arguments: >
        -OutputPath '$(Build.ArtifactStagingDirectory)'
        -Version '$(Version)'
        -OperatingSystem '${{ parameters.OSName }}'
        -Architecture '$(Architecture)'
        -SelfContained
        -ReadyToRun

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)
      ArtifactName: $(PipelineArtifactName)_$(System.JobName)
      CustomCondition: and(succeededOrFailed(), ne(variables['NoPackagesChanged'],'true'))
