parameters:
- name: ContainerRegistry
  type: string
  default: 'azuresdkimages'
- name: DeploymentEnvironment
  type: string
  default: 'public'
- name: ReleaseRun
  type: boolean
  default: false
- name: Version
  type: string

variables:
  imageName: ${{ format('{0}/{1}', parameters.DeploymentEnvironment, 'azure-sdk/azure-mcp')}}
  containerRegistryUrl: ${{ format('{0}.azurecr.io', parameters.ContainerRegistry) }}
  isRelease: ${{ eq(parameters.ReleaseRun, 'true') }}

jobs:
- job: DockerBuildAndPublish
  pool:
    name: $(LINUXPOOL)
    image: $(LINUXVMIMAGE)
    os: linux

  ${{ if $isRelease }}:
    templateContext:
      outputs:
      - output: containerImage
        image: image:tag
        remoteImage:
        - $(containerRegistryUrl).azurecr.io/$(imageName):$(parameters.Version)

  steps:

  - task: AzureCLI@2
    condition: and(succeeded(), $isRelease)
    displayName: Login to ${{ parameters.ContainerRegistry }}
    inputs:
      azureSubscription: "Azure SDK Engineering System"
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az acr login --name $(containerRegistry)

  - task: 1ES.BuildContainerImage@1
    displayName: Build Docker Image
    inputs:
      path: $(configPath)
      image: image:tag
      enableNetwork: ${{ if $isRelease }}
      useBuildKit: ${{ if $isRelease }}