parameters:
- name: TimeoutInMinutes
  type: number
  default: 120

jobs:
- job: SignAndPack
  displayName: "Sign and Pack"
  timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
  pool: # Binary signing of mac bits needs to happen on mac see https://github.com/Azure/azure-mcp/blob/4ff032fafc77bc618738879b7028665c0de2e632/eng/scripts/Compress-ForSigning.ps1#L40
    name: $(MACPOOL)
    vmImage: $(MACVMIMAGE)
    os: macos
  steps:
  - checkout: self

# Process dotnet based binaries.

  - task: DownloadPipelineArtifact@2
    displayName: Download dotnet artifacts
    inputs:
      source: current
      patterns: $(PipelineArtifactName)_*/dotnet/**
      path: $(Pipeline.Workspace)/dotnet

  - task: Powershell@2
    displayName: "Compress packages"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Compress-ForSigning.ps1
      arguments: >
        -ArtifactsPath '$(Pipeline.Workspace)/dotnet'
        -ArtifactPrefix '$(PipelineArtifactName)_'
        -OutputPath '$(Build.ArtifactStagingDirectory)/signed/dotnet'

  - template: pipelines/steps/binary-signing.yml@azure-sdk-build-tools
    parameters:
      SigningKeyCode: 'CP-230012' # MS Cert
      BinaryPath: $(Build.ArtifactStagingDirectory)/signed/dotnet
      BinaryPattern: |
        win-*/**/azmcp.dll
        win-*/**/azmcp.exe
        win-*/**/AzureMcp*.dll

  - template: pipelines/steps/binary-signing.yml@azure-sdk-build-tools
    parameters:
      SigningKeyCode: 'CP-231522' # MS 3rd Party Cert
      BinaryPath: $(Build.ArtifactStagingDirectory)/signed/dotnet
      BinaryPattern: |
        win-*/**/ModelContextProtocol*.dll
        win-*/**/Npgsql.dll
        win-*/**/OpenAI.dll
        win-*/**/OpenTelemetry*.dll
        win-*/**/YamlDotNet.dll

  - template: pipelines/steps/azd-cli-mac-signing.yml@azure-sdk-build-tools
    parameters:
      MacPath: $(Build.ArtifactStagingDirectory)/signed/dotnet
      MacPattern: "**/*.zip"

  - task: Powershell@2
    displayName: "Expand packages"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Expand-AfterSigning.ps1
      arguments: >
        -Path '$(Build.ArtifactStagingDirectory)/signed/dotnet'

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)/signed/dotnet
      ArtifactName: $(PipelineArtifactName)_signed_dotnet
      SbomEnabled: ${{ ne(variables['Build.Reason'], 'PullRequest') }}

  - task: Powershell@2
    displayName: "Pack modules"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Pack-Modules.ps1
      arguments: >
        -ArtifactsPath '$(Build.ArtifactStagingDirectory)/signed/dotnet'
        -OutputPath '$(Build.ArtifactStagingDirectory)/packed/dotnet'
        -Version '$(Version)'

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)/packed/dotnet
      ArtifactName: $(PipelineArtifactName)_packed_dotnet
      SbomEnabled: ${{ ne(variables['Build.Reason'], 'PullRequest') }}

# Process native based binaries.

  - task: DownloadPipelineArtifact@2
    displayName: Download native artifacts
    inputs:
      source: current
      patterns: $(PipelineArtifactName)_*/native/**
      path: $(Pipeline.Workspace)/native

  - task: Powershell@2
    displayName: "Compress packages"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Compress-ForSigning.ps1
      arguments: >
        -ArtifactsPath '$(Pipeline.Workspace)/native'
        -ArtifactPrefix '$(PipelineArtifactName)_'
        -OutputPath '$(Build.ArtifactStagingDirectory)/signed/native'

  - template: pipelines/steps/binary-signing.yml@azure-sdk-build-tools
    parameters:
      SigningKeyCode: 'CP-230012' # MS Cert
      BinaryPath: $(Build.ArtifactStagingDirectory)/signed/native
      BinaryPattern: |
        win-*/**/azmcp.dll
        win-*/**/azmcp.exe
        win-*/**/AzureMcp*.dll

  - template: pipelines/steps/binary-signing.yml@azure-sdk-build-tools
    parameters:
      SigningKeyCode: 'CP-231522' # MS 3rd Party Cert
      BinaryPath: $(Build.ArtifactStagingDirectory)/signed/native
      BinaryPattern: |
        win-*/**/ModelContextProtocol*.dll
        win-*/**/Npgsql.dll
        win-*/**/OpenAI.dll
        win-*/**/OpenTelemetry*.dll
        win-*/**/YamlDotNet.dll

  - template: pipelines/steps/azd-cli-mac-signing.yml@azure-sdk-build-tools
    parameters:
      MacPath: $(Build.ArtifactStagingDirectory)/signed/native
      MacPattern: "**/*.zip"

  - task: Powershell@2
    displayName: "Expand packages"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Expand-AfterSigning.ps1
      arguments: >
        -Path '$(Build.ArtifactStagingDirectory)/signed/native'

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)/signed/native
      ArtifactName: $(PipelineArtifactName)_signed_native
      SbomEnabled: ${{ ne(variables['Build.Reason'], 'PullRequest') }}

  - task: Powershell@2
    displayName: "Pack modules"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Pack-Modules.ps1
      arguments: >
        -ArtifactsPath '$(Build.ArtifactStagingDirectory)/signed/native'
        -OutputPath '$(Build.ArtifactStagingDirectory)/packed/native'
        -Version '$(Version)'
        -BuildNative

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)/packed/native
      ArtifactName: $(PipelineArtifactName)_packed_native
      SbomEnabled: ${{ ne(variables['Build.Reason'], 'PullRequest') }}