parameters:
- name: TimeoutInMinutes
  type: number
  default: 120
- name: SkipSigning
  type: boolean
  default: false

jobs:
- job: SignAndPackVSIX
  ${{ if parameters.SkipSigning }}:
    displayName: "Pack VSIX"
  ${{ else }}:
    displayName: "Sign and Pack VSIX"
  condition: and(succeededOrFailed(), ne(variables['Skip.Analyze'], 'true'))
  timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
  strategy:
    matrix:
      linux_x64:
        ArtifactName: vsix-unsigned_linux_x64
      linux_arm64:
        ArtifactName: vsix-unsigned_linux_arm64
      osx_x64:
        ArtifactName: vsix-unsigned_osx_x64
      osx_arm64:
        ArtifactName: vsix-unsigned_osx_arm64
      win_x64:
        ArtifactName: vsix-unsigned_win_x64
      win_arm64:
        ArtifactName: vsix-unsigned_win_arm64
  pool:
    name: $(MACPOOL)
    vmImage: $(MACVMIMAGE)
    os: macos
  steps:
    - checkout: self

    - download: current
      displayName: Download artifacts

    - task: PowerShell@2
      inputs:
        targetType: filePath
        filePath: eng/scripts/New-VsixSigningManifest.ps1
        arguments: -Path $(Pipeline.Workspace)\${{ matrix.ArtifactName }}
        pwsh: true
      displayName: Create signing manifest

    - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual') }}:
      - template: pipelines/steps/azd-vscode-signing.yml@azure-sdk-build-tools
        parameters:
          Path: $(Pipeline.Workspace)\${{ matrix.ArtifactName }}
          Pattern: '*.vsix'

    - ${{ else }}:
      - pwsh: Write-Host "Skipping signing. Build reason - $(Build.Reason)"
        displayName: Signing process skipped for non-release build

    - pwsh: |
        New-Item -ItemType Directory -Path signed -Force
        Copy-Item vsix\*.vsix signed\ -Force
      displayName: Copy signed VSIX for publishing
      condition: always()

    - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
      parameters:
        ArtifactPath: signed
        ArtifactName: vsix-signed_${{ matrix.ArtifactName }}
        SbomEnabled: ${{ ne(variables['Build.Reason'], 'PullRequest') }}