name: Auto-assign Copilot Reviewer

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  assign-copilot:
    runs-on: ubuntu-latest
    steps:
      - name: Add Copilot as reviewer
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            
            try {
              await github.rest.pulls.requestReviewers({
                owner,
                repo,
                pull_number,
                reviewers: ['copilot']
              });
              console.log('Successfully added @copilot as reviewer');
            } catch (error) {
              console.log('Error adding @copilot as reviewer:', error.message);
            }
