name: Release Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
  workflow_dispatch:
    inputs:
      version_increment:
        description: 'Version increment type (major, minor, patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

env:
  DOTNET_VERSION: '9.0.x'
  ARTIFACT_PREFIX: 'azmcp'
  PROJECT_PATH: 'src/AzureMCP.csproj'

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Read version
      id: read-version
      run: |
        if ! VERSION=$(grep -oP '(?<=<Version>)[^<]+' "${{ env.PROJECT_PATH }}"); then
          echo "Failed to read version from project file"
          exit 1
        fi
        echo "current=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Calculate new version
      id: set-version
      run: |
        IFS='.' read -r major minor patch <<< "${{ steps.read-version.outputs.current }}"
        
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          case "${{ inputs.version_increment }}" in
            "major")
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            "minor")
              minor=$((minor + 1))
              patch=0
              ;;
            "patch")
              patch=$((patch + 1))
              ;;
          esac
          NEW_VERSION="$major.$minor.$patch"
        else
          NEW_VERSION="${{ steps.read-version.outputs.current }}"
        fi
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        
    - name: Update .csproj version and push changes
      if: github.event_name == 'workflow_dispatch'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Updating .csproj version"
        sed -i "s/<Version>.*<\/Version>/<Version>${{ steps.set-version.outputs.version }}<\/Version>/" ${{ env.PROJECT_PATH }}
        
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add ${{ env.PROJECT_PATH }}
        git commit -m "Bump version to ${{ steps.set-version.outputs.version }}"
        git tag "v${{ steps.set-version.outputs.version }}"
        git push
        git push --tags

  test:
    needs: version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Test
      run: |
        cd tests
        dotnet test -c Release

  build:
    needs: [test, version]
    name: Build (${{ matrix.os }})
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows
            rid: win-x64
            extension: .exe
          - os: linux
            rid: linux-x64
            extension: ''
          - os: osx
            rid: osx-x64
            extension: ''
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
      
    - name: Build
      run: |
        cd src
        dotnet publish -c Release -r ${{ matrix.rid }} \
        --self-contained true \
        -p:PublishSingleFile=true \
        -p:PublishTrimmed=false \
        -p:UseAppHost=true \
        -p:IncludeNativeLibrariesForSelfExtract=true \
        -p:Version=${{ needs.version.outputs.version }}

    - name: Package Artifacts
      run: |
        mkdir -p artifacts
        cd src/bin/Release/net9.0/${{ matrix.rid }}/publish
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          # For PR builds, just copy the binary with PR number in name
          cp azmcp${{ matrix.extension }} ../../../../../../artifacts/${{ env.ARTIFACT_PREFIX }}-pr${{ github.event.pull_request.number }}-${{ matrix.os }}${{ matrix.extension }}
        else
          # For releases and main pushes, create zip package
          zip ../../../../../../artifacts/${{ env.ARTIFACT_PREFIX }}-${{ matrix.os }}.zip azmcp${{ matrix.extension }}
        fi

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event_name == 'pull_request' && format('pr{0}-{1}', github.event.pull_request.number, matrix.os) || format('{0}-{1}', env.ARTIFACT_PREFIX, matrix.os) }}
        path: artifacts/*
        if-no-files-found: error
        retention-days: ${{ github.event_name == 'pull_request' && 5 || 90 }}

  release:
    needs: [version, build]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ env.ARTIFACT_PREFIX }}-*
        merge-multiple: true
        path: artifacts
        
    - name: List Artifacts Directory
      run: |
        echo "Current directory:"
        pwd
        echo "Artifacts directory structure:"
        find artifacts -type f
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ needs.version.outputs.version }}
        name: Release v${{ needs.version.outputs.version }}
        files: |
          artifacts/${{ env.ARTIFACT_PREFIX }}-windows.zip
          artifacts/${{ env.ARTIFACT_PREFIX }}-linux.zip
          artifacts/${{ env.ARTIFACT_PREFIX }}-osx.zip

  upload-latest:
    needs: [version, build]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Upload to Latest Build
      uses: actions/upload-artifact@v4
      with:
        name: latest-build-v${{ needs.version.outputs.version }}
        path: artifacts/**/${{ env.ARTIFACT_PREFIX }}-*.zip
        if-no-files-found: error
        retention-days: 5